### ISSUE TITLE
Firefox 38 : New Option menu

### ISSUE THREAD

**Issue by Ar-n** [ttaubert/customizable-shortcuts#100]
Hi,
First, thank to the extension author, it's a great help in my daily work.
but since Firefox 38, the menu scheme is totaly different, it shows in a tab, with a total different look.
In consequence, customizable-shortcut menu disappears.

Regards,
Arno

**Comment by ttaubert** [comment]
Thanks for reporting!

Please install v0.9.6 that is currently pending review and will probably be for a while:

https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/versions/?page=1#version-0.9.6

**Comment by wcrighton** [comment]
I have installed it and it did fix the problem - the icon appeared in my bar and I'm able to view and modify the shortcuts.
Thanks man
-wc
