### ISSUE TITLE
0.9.6 : not showing button

### ISSUE THREAD

**Issue by Draky50110** [ttaubert/customizable-shortcuts#101]
Hello.

I installed 0.9.6 (FF 38 on Ubuntu) and I don't see the button to customize :( 

Possible to have the 0.9.5 xpi ?
Or a bugfix ?

Thanks :)

**Comment by ttaubert** [comment]
I can't reproduce this. A fresh install of v0.9.6 on my Ubuntu machine with Firefox 38 works just fine and shows the toolbar button.

**Comment by Draky50110** [comment]
Deleted F + local profile.
Reinstall FF.
Nothing appears :/

**Comment by wcrighton** [comment]
I don't think it'll fix your problem but if you go to Taubert's github you
can download his source which includes the 095 xpi. I don't think it'll fix
the problem because I installed 096 on my ubuntu 14.04.02 compiz/unity
desktop and it shows up fine in ff 38.0
-wc

--
William Crighton
Capital City Consultants LLC.
4301 W. William Cannon Drv.
Suite B150-288
Austin TX 78749
wcrighton@capitalcityconsultants.com
512.694.4298

My Calendar
<http://www.google.com/calendar/embed?src=wcrighton%40capitalcityconsultants.com&ctz=America/Chicago>

**Comment by ttaubert** [comment]
Draky, do you see any errors in the Browser Console after starting Firefox?

**Comment by Draky50110** [comment]
Sorry but I don't know how to "look at browser console" and when.
Is it using F12 key ?

**Comment by ttaubert** [comment]
Ctrl+Shift+J shows the Browser Console. Maybe there are a few helpful error messages.

**Comment by Draky50110** [comment]
Just tried to enable/disable only your extension, here is the console result :
http://gilles.wittezaele.fr/paste/?f0f95634bdefca38#4JN6mkFOYP0dWEyeOHczaaRalbpOui3KF3DnjILYzyc=

When enaling/disabling a little more : http://gilles.wittezaele.fr/paste/?9cdf0218117cbf6f#fCFDb6ezYQ43lYYzTfiPtL37ZAQQPCWqJ2mXxqfz260=

Not sure it is related.

**Comment by ttaubert** [comment]
Thanks! That unfortunately doesn't seem related... still no idea why it isn't working for you, sorry :|

**Comment by ttaubert** [comment]
After installing the add-on, did you go into customization mode to check whether the toolbar button is in there somewhere? Maybe it's hidden by default for some reason? Can't imagine that though if it doesn't even work with a clean profile...

**Comment by Draky50110** [comment]
Ok, not a real problem.
And yes, I checked my custom icons before asking ;)
Here is a screenshot : 
[Imgur](http://i.imgur.com/5O5NE9c.png)

**Comment by jakeyeung** [comment]
I would like to confirm that I also cannot find the icon in the toolbar after updating to 0.9.6. 

I am running arch 32-bit version.

I have tried reinstalling firefox but I still cannot find the toolbar.

Any idea on what may be the problem?

**Comment by jakeyeung** [comment]
I removed the extension, reinstalled firefox then downloaded the toolbar via: https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.6.xpi?raw=true 

And that seemed to work. I see the toolbar now.

**Comment by bcse** [comment]
I also got this issue. And @jakeyeung's solution works for me.

**Comment by fda77** [comment]
@jakeyeung: Thanks, that works!

**Comment by givensp** [comment]
I've had the Toolbar Button, and always had to go to > Tools > Options > Custom Shortcuts!
@jakeyeung: Thanks, now I have the Button. That'll work so much better!

**Comment by Visgean** [comment]
I am using latest firefox developer edition and I can also confirm this issue, release 0.9.6 works.

**Comment by Craig620** [comment]
Same issue on with Firefox 38 on windows. On one machine the auto updated pulled the new version, and old keystoke mod quit working. Can't remember last time I opened config page to modify keystrokes. Now its not there. On another machine that did not update, not problem.
No icon avail for CustShort to add to toolbar. Tools/Options is in the menu, but nothing beneath that for "customize shortcuts". Really don't want to reset profile and lose other extensions. Is there another solution?

**Comment by ttaubert** [comment]
Craig, this is not the same issue. v0.6 stopped being supported in Firefox 38 and you'll have to download the new version: https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.6.xpi?raw=true

**Comment by Craig620** [comment]
New install of FF38.05. New 0.96 version of custshort. New FF profile.
Still no choice in tools options to customize CS settings, or ability to add a CS button to toolbar.
Really liked using this addon. Still looking for advice to restore functionality. thx
<a href="http://imgbox.com/CkBJXXqa" target="_blank"><img src="http://5.t.imgbox.com/CkBJXXqa.jpg" alt="image host"/></a> <a href="http://imgbox.com/LXBb4PBU" target="_blank"><img src="http://7.t.imgbox.com/LXBb4PBU.jpg" alt="image host"/></a>

**Comment by Decker108** [comment]
Same problem here on FF 38.0.5 on OSX, using 0.96. Jakeyeungs solution tried but not working.

**Comment by ttaubert** [comment]
Ummm... Craig. Do you see the toolbar button that looks like a "shortcut symbol" in the upper right of the window? That's the add-on. The new version isn't located in Preferences anymore.

**Comment by ttaubert** [comment]
Decker, did you also miss the toolbar button or is it really not there?

**Comment by Decker108** [comment]
@ttaubert The toolbar button really is not there, and it's also not in the "Additional tools and features" menu.

**Comment by Craig620** [comment]
Thank you for helping me find "the forest in the trees" Tim!
I would like to suggest that if there were an "options" button on the add-ons page like there is for other add-ons, it would be helpful to a lot of people.

<a href="http://imgbox.com/WAtvbbHG" target="_blank"><img src="http://9.t.imgbox.com/WAtvbbHG.jpg" alt="image host"/></a>

**Comment by tim-kretschmer-c2fo** [comment]
I had this same problem when installing from [Mozilla's add on site](https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/). However, the latest download from your releases page on GitHub (0.9.7) shows the toolbar button as expected.

**Comment by Draky50110** [comment]
It is ok for me with 0.9.7 :)

**Comment by Decker108** [comment]
It started working for me after a restart... weird.
