### ISSUE TITLE
Add-on not working in Firefox 38.0.1 on OSX 10.10.2

### ISSUE THREAD

**Issue by Decker108** [ttaubert/customizable-shortcuts#103]
As of 38.0.1, Firefox no longer responds to my shortcuts for tabs (CTRL+1 though CTRL+8 to switch between tabs 1-8, CTRL+9 to switch to last tab). Other shortcuts seem to work, but I can no longer find the customizable shortcuts menu in the tools menu.

**Comment by ttaubert** [comment]
Not sure why it's not working but to get the add-on back you need to install the latest version until AMO got around to properly review it, sorry.

https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.6.xpi?raw=true

**Comment by Decker108** [comment]
@ttaubert Reinstalling worked, thanks.
