### ISSUE TITLE
No configuration tab in firefox 38.0.1.

### ISSUE THREAD

**Issue by tioteath** [ttaubert/customizable-shortcuts#105]
Configuration tab is missing in new Firefox preferences. 
Add-on version: 0.9.8.

**Comment by ttaubert** [comment]
The add-on is now a toolbar button. Please check for a new button in the upper-right of the browser window or in the main browser menu.

**Comment by tioteath** [comment]
Unfortunately, I had to remove `#navbar` by modifying `userStyle.css`, as it stays visible in fullscreen , so no 'main bower menu'. How can I find this button, then? It isn't available in `Customize...`  menu.
