### ISSUE TITLE
New window/tab shortcuts don't change

### ISSUE THREAD

**Issue by pneumotube** [ttaubert/customizable-shortcuts#106]
Something wrong has happened after last extention update (0.9.8).

My settings: http://i.imgur.com/pBUqUTe.png

Browser settings after FF (38.0.5) restart: http://i.imgur.com/jPQrhxW.png

Ctrl + N simply doesn't work.

**Comment by GoshaKucenko** [comment]
I have similar problem too.

It is due to localization.

After last update edited shortcuts doesn't work when language set to not English one.

**Comment by ttaubert** [comment]
> Browser settings after FF (38.0.5) restart: http://i.imgur.com/jPQrhxW.png

The new shortcuts aren't supposed to be reflected in the menu.

> Ctrl + N simply doesn't work.

I just tried with a Russian build and I can set "New Tab" to Ctrl+N, it works even after a restart. Can you please describe exactly the steps you do and what's not working?

**Comment by pneumotube** [comment]
​GoshaKucenko made a good point. Ctrl + N doesn't work when system language
is set to English and works when language is Russian.

​This is definitely a new​ problem as I've used FF with this shortcut for a
long time on both system languages without such issue.


2015-06-30 20:58 GMT+03:00 Tim Taubert <notifications@github.com>:

**Comment by ttaubert** [comment]
Well that doesn't help. Can anyone of you please give me steps to reproduce this?

**Comment by pneumotube** [comment]
1. Ctrl + N = New Tab in CS extention.

2. Windows locale (system lang) = En.

3. FF language = Ru.

Ctrl + N does nothing.

Please specify what additional information you need.

2015-06-30 21:47 GMT+03:00 Tim Taubert <notifications@github.com>:

**Comment by GoshaKucenko** [comment]
I also added steps to reproduce here: https://github.com/ttaubert/customizable-shortcuts/issues/107

**Comment by pneumotube** [comment]
Hi! Any update on this issue? It's extremely annoying to use a mouse for open a new tab when addicted to Ctrl + N shortcut.

**Comment by dgutov** [comment]
I've been annoyed by this for a while. You don't need to change the locale, or download a Russian build of Firefox to reproduce. Just set up an alternative, Russian layout.

Set up the shortcuts using an English layout, then switch to Russian - and they don't work. Every shortcut works as if this extension is not installed. Which is a pain, considering that I rebind `Ctrl-Shift-W`.

Ubuntu 14.10, `LANG en_US.UTF-8`.

**Comment by ttaubert** [comment]
Same as #107.
