### ISSUE TITLE
Customizable Shortcuts UI doesn't appear

### ISSUE THREAD

**Issue by MegaJar** [ttaubert/customizable-shortcuts#108]
I'd been using this add-on quite happily for a while, but now the UI components have stopped appearing. There's no button in any of the toolbars, no menu item in the FF menu bar, and no preference tab in the FF Options dialog. How do I get the UI elements back?

I have Firefox 38.0.5, and Customizable Shortcuts version 0.9.8. Per suggestions in the add-on's reviews, I tried downgrading to 0.9.7, but that didn't work either.

**Comment by depoulo** [comment]
:heavy_check_mark: found it in the upper right corner

**Comment by MegaJar** [comment]
Ah, I see the problem. The "Classic Theme Restorer" add-on was interfering with the display of the "Customizable Shortcuts" icon. I was able to play around with the settings, and now the icon appears properly.

However, there's still no "Customizable Shortcuts" tab in the main FF preferences dialog, and I'm pretty sure there used to be one. I much prefer it to be there, rather than in the toolbar -- changing keyboard shortcuts isn't something I do very frequently, so it doesn't really need a quick-access toolbar button, IMO.

**Comment by lostdj** [comment]
@MegaJar 
> The "Classic Theme Restorer" add-on was interfering with the display of the "Customizable Shortcuts" icon. I was able to play around with the settings, and now the icon appears properly.

How did you fix it?

**Comment by ttaubert** [comment]
Closing because I unfortunately can't fix anything another add-on breaks. Thanks for figuring it out!

**Comment by depoulo** [comment]
Waitaminute. So where is now the UI for adding new shortcuts?
