### ISSUE TITLE
Update question

### ISSUE THREAD

**Issue by IMeanReallyNow** [ttaubert/customizable-shortcuts#110]
Hi. I currently have version 0.9.0 installed and have downloaded 0.9.8 but I am not sure how to install it, as I normally install plugins using an xpi file. 

I am using the Portable Apps version of FF. I have updated C-S before, but to be honest, do not recall what needs to be copied from the zip and where it needs to be placed in the portable FF installation. 

(The reason I went looking for an update is that I am hoping it is possible to assign a custom shortcut key to the new FF Reading mode, which AFAICT is not available in C-S 0.9.0. 

Thank you!

**Comment by IMeanReallyNow** [comment]
Actually... I found the xpi in the zip file and got the update installed. 

But now I'm wondering, can a shortcut be made through C-S for Reader View? I don't see it in the list of available shortcuts. 

Thanks again.

**Comment by ttaubert** [comment]
> But now I'm wondering, can a shortcut be made through C-S for Reader View? I don't see it in the list of available shortcuts.

There is no <key> element registered for that shortcut it seems. I might add support for that specific action if the demand is large but that should be tracked in its own ticket.
