### ISSUE TITLE
Firefox v. 33?

### ISSUE THREAD

**Issue by VLM1** [ttaubert/customizable-shortcuts#114]
The Firefox page at https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/ says this extension is not available for Fx. 33. Will it run properly, if I bypass version checking?

FYI, I'm still on that version, because I got tired of Firefox installers wrecking my installations. So I stopped using them, at least for a bit. :) Sometimes I feel tempted to return to v. 17.

**Comment by ypid** [comment]
That is a really bad idea if your data stored on your computer means anything to you and are not running your FF 33 in Qubes OS or something.

https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/

**Comment by ttaubert** [comment]
> FYI, I'm still on that version, because I got tired of Firefox installers wrecking my installations. So I stopped using them, at least for a bit. :) Sometimes I feel tempted to return to v. 17.

You really should run the latest Firefox version, 33 will contain at least a dozen critical security vulnerabilities that are fixed in the latest release. For other reasons, the add-on doesn't work with anything before 38 if I remember correctly.

**Comment by VLM1** [comment]
Thank you Tim. I once used the extension with 33, but that was a while ago. 

 

My impression is that many of the vulnerabilities being fixed are those introduced in the rapid release process. In other words, my impression is that many of the bugs fixed by 40 were introduced in the 30s to begin with. Is your impression different?

 

Thanks,

Elchanan
