### ISSUE TITLE
Shortkey to came back to previous tab

### ISSUE THREAD

**Issue by M5oul** [ttaubert/customizable-shortcuts#116]
Could you add a shortkey to came back to the previous tab as `Alt + tab` combination.

**Comment by ttaubert** [comment]
Look for "Switch to Next Tab" and "Switch to Previous Tab". Those should do what you want.

**Comment by M5oul** [comment]
I think you do not understand what I means. Try [this configuration with `Alt + tab`](https://support.mozilla.org/en-US/questions/955292) in your browser to see what I mean about going back to previous tab. By "previous", I mean the historically one and not the physical one.

**Comment by ttaubert** [comment]
Ah I see, afaik there's no action for that in Firefox. That would probably deserve its own add-on...

**Comment by M5oul** [comment]
Sad, this could be a great feature. I use this command almost all the time. And `Ctrl + tab` is not easy to do on my keyboad. Thanks again.
