### ISSUE TITLE
please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [ttaubert/customizable-shortcuts#123]
Perhaps something like

    Copyright 2011-2015 Tim Taubert <contact@email.com>

Thanks.

**Comment by ttaubert** [comment]
The code has a license, why would you need a copyright statement?

**Comment by onlyjob** [comment]
Standard practice and a requirement for packaging. Many licenses such as GPL and Apache have specific instructions to include copyright statement to license grant. MPL-2.0 only mentions that: "You may add additional accurate notices of copyright ownership" but really you should always add copyright statement. It is the best to do so.

**Comment by ttaubert** [comment]
Well, I don't want to package it. It's available on addons.mozilla.org and that's fine. I don't care about copyright tbh.

**Comment by onlyjob** [comment]
Fair enough but some people care hence this ticket was opened. How hard it is to include copyright statement to README? I do not understand your resistance. :(
