### ISSUE TITLE
`install.rdf` is missing -- how to generate?

### ISSUE THREAD

**Issue by onlyjob** [ttaubert/customizable-shortcuts#124]
I would like to re-build .xpi file but `install.rdf` appears to be missing and there is no `Makefile` to generate it... Please advise.

**Comment by ttaubert** [comment]
You can use `jpm xpi` to build. See here https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm

**Comment by onlyjob** [comment]
No unfortunately I can't use this command as we do not have SDK in Debian yet (maybe some older build tools are available).
But `install.rdf` is just a small XML file -- maybe it can be included outside of pre-built .xpi file?

Also it could be nice to include brief build instructions in README (e.g. `jpm xpi`).
Is there any other ways to generate `install.rdf`?

**Comment by ttaubert** [comment]
That's how the new add-on SDK works, you can just download it. You don't need something that's in Debian or not.
