### ISSUE TITLE
Linux Super key

### ISSUE THREAD

**Issue by theeternalsw0rd** [ttaubert/customizable-shortcuts#25]
Cannot use the Super key in any combinations.

**Comment by ttaubert** [comment]
v0.9.3 (the current .xpi in the master branch) deals well with the Windows key on Windows but only if the desired shortcut isn't provided by the OS. Win+J for example works, while Win+E doesn't. I'll try with Linux and report back.

**Comment by ttaubert** [comment]
This probably varies from distribution to distribution (or rather WM), Ubuntu doesn't allow using the Super key at all. Closing this issue, there's nothing I can do about that, sorry.

**Comment by ttaubert** [comment]
v0.9.4, the current .xpi in the master branch WFM on Ubuntu. I can set shortcuts with Alt and Super that aren't taken by the system. Please give it a try!

**Comment by eigengrau** [comment]
Awesome, thanks! This seems to work at least with super, meta and control. Sadly, it doesn’t work for all modifiers in general (the ones shown by `xmodmap`, i. e., shift, lock, mod1-mod5). E. g., my mod2, bound to the keysym hyper is shown as «super» in customizable shortcuts. Modifiers that work as higher-level shifts are not recognized at all. But maybe Firefox just doesn’t pass them on correctly.
