### ISSUE TITLE
alt+d

### ISSUE THREAD

**Issue by zhangweiwu** [ttaubert/customizable-shortcuts#45]
Alt+d opens location bar like Ctrl+L or F6 does.

This is to request to allow Alt+d to be remapped or removed, so that to give space to EMACS editing shortcut key (alt+d means delete the current word in EMACS).

Implementing this feature would let users forgo the age-old keyconfig.xpi which can disable alt+d purpose:  http://mozilla.dorando.at/keyconfig.xpi

**Comment by Keith94** [comment]
0.9.0 added support for disabling shortcuts.
https://github.com/ttaubert/customizable-shortcuts/raw/master/customizable-shortcuts.xpi
