### ISSUE TITLE
Ability to rebind "Open context menu" shortcut

### ISSUE THREAD

**Issue by maxless** [ttaubert/customizable-shortcuts#54]
Please add this. By default it's Shift-F10 in Windows/Linux and Ctrl-Space on Mac.

**Comment by ttaubert** [comment]
Please check out v0.9.3, the latest .xpi file in the master branch. I tested with my Windows machine that has a context menu button. I can indeed rebind it but it seems like I can't stop the menu from popping up.

**Comment by maxless** [comment]
I've downloaded the Firefox 38 beta, customizable-shortcuts@timtaubert.de-0.9.5.xpi from master branch and installed it, but I don't see anything like "Open context menu" or Shift-F10 in the list of shortcuts.

http://screencast.com/t/542QJKNoSoMO

**Comment by ttaubert** [comment]
Ah... I misread the issue. I thought it was about using the "Contextmenu" key for other actions. The key itself isn't bound to any specific action in Firefox so that's why it's not showing up.

**Comment by maxless** [comment]
Sorry, I wasn't clear enough. I'd like to use some other key combination to
open context menu.

2015-05-13 13:18 GMT+04:00 Tim Taubert <notifications@github.com>:
