### ISSUE TITLE
Preferences inaccessible in 31.3.0 (Iceweasel ESR)

### ISSUE THREAD

**Issue by mbg71** [ttaubert/customizable-shortcuts#73]
I installed the XPI from master dated Nov 12. Extension appears to be active, but no button appears in the preference window (not after restart either).

Version is iceweasel ESR 31.3.0 from the mozilla.debian.net wheezy-backports iceweasel-esr repo.

**Comment by FredMcD-HotMail** [comment]
Please read this; https://github.com/ttaubert/customizable-shortcuts/issues/83

**Comment by ttaubert** [comment]
v0.9 will use a toolbar button.
