### ISSUE TITLE
No way to get to prefs in 37.0a1 (2014-12-10) ?

### ISSUE THREAD

**Issue by jbclements** [ttaubert/customizable-shortcuts#74]
If I understand correctly, it looks like Mozilla is moving away from a separate-window preferences pane, and toward a simple "about:preferences" URL.  Unfortunately, it appears to me that this makes Customizable Shortcuts unusable, because there's no way to get to its preferences pane.

Apologies in advance if I've missed something obvious.

Steps to reproduce:

1) Choose Nightly>Preferences
2) See new tab (about:preferences), with no way to reach Customizable Shortcuts settings.

**Comment by Keith94** [comment]
It has been updated to use a separate button with a panel as of 0.9.0. Install it here: https://github.com/ttaubert/customizable-shortcuts/raw/master/customizable-shortcuts.xpi

See screenshots for usage: https://github.com/ttaubert/customizable-shortcuts/blob/master/README.md

**Comment by brknsoul** [comment]
I don't get the c-s button, even with all other addons disabled. It doesn't appear in my tooltip, or in Customize. (using 0.9.0)

**Comment by Keith94** [comment]
Hmm, I'm not sure what could cause that. In case your default profile became corrupted somehow, you could test the add-on in a new profile to see if it works there.

See https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by brknsoul** [comment]
Made a brand new profile, manually installed c-s.xpi, restarted firefox, still no button;
http://i.imgur.com/RWPAB4h.jpg

Perhaps you could make an options button on the addon page to pop up the relevant frame? Since one only sets up keybindings once.

**Comment by Keith94** [comment]
Not really possible on my side, since I'm not the developer.

I tried to access the panel directly in a tab (from: chrome://customizable-shortcuts/content/panel.xul), but the shortcuts do not appear in there, sadly.

**Comment by brknsoul** [comment]
Odd, Firefox just updated to 35.0.1 (from 34-something) and the button is now there.

**Comment by FredMcD-HotMail** [comment]
Please read this; https://github.com/ttaubert/customizable-shortcuts/issues/83

**Comment by ttaubert** [comment]
Closing, the toolbar button will replace the pref dialog addition in v0.9
