### ISSUE TITLE
Remove shortcut & Win key

### ISSUE THREAD

**Issue by nonentity1001** [ttaubert/customizable-shortcuts#75]
Needs a remove shortcut - sometimes the best way to get rid of an annoyance is to remove it rather than replace 

The Win key, if its to be supported at all, should be treated as a Modifier key like shift/ctrl/alt not as a keystroke.  Given FF is multi platform I don't think it should be 'recognised' at all

**Comment by Keith94** [comment]
0.9.0 added support for disabling shortcuts.
https://github.com/ttaubert/customizable-shortcuts/raw/master/customizable-shortcuts.xpi

**Comment by romain-dartigues** [comment]
Version 0.9.0 does not show in "Options" panel in Firefox 36, even with the `browser.preferences.inContent = false` trick and even after a browser restart.

**Comment by Keith94** [comment]
It's a toolbarbutton. http://i.imgur.com/7ddKaQQ.png

**Comment by romain-dartigues** [comment]
You are right, sorry; i though it would also show in the Tool menu. Working fine.
