### ISSUE TITLE
How to access 

### ISSUE THREAD

**Issue by IMeanReallyNow** [ttaubert/customizable-shortcuts#76]
Hello and happy new year. 

I have the version 0.9.0 of the extension installed, and enabled, but I am unable to find it on any of the menus. 

I've accessed it in the past, but now I can't find it anywhere. 

Using FF 34.0.5 on Windows 7.

Thanks. 

Sorry for what is probably a dumb question.

**Comment by Tengra** [comment]
Same query: I install it, and now what ? 
Can't see anything to click on. 
Can't see any key combination to press to bring up something 
firefox tells me it's installed but where ? how do I interact with it ? 
thanks
T

**Comment by IMeanReallyNow** [comment]
I'd forgotten about this but still would like to know. Can you be more precise about how to actually use the plugin? Where do I find its UI? Which "Options" tab? 

When I go to the one under Tools-->Options, in the dialog that opens, I don't see anything on any of the tabs that has anything to do with this plug in. 

A clue would be really appreciated. Thanks!

**Comment by Keith94** [comment]
In v0.9.0 there should be a button added to the toolbar as shown in [this screenshot](http://i.imgur.com/7ddKaQQ.png), where you can access everything. If it's not there, you may need to add it using Firefox's [customize feature](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars).

**Comment by IMeanReallyNow** [comment]
I've downloaded v0.9.0. But where exactly do I place its folders? I'm using Firefox Portable. I'm able to get the basic dialog, but it is in a "grayed out" state. Nothing responds to clicks. Thanks.

**Comment by IMeanReallyNow** [comment]
The zip I downloaded contains a folder named customizable-shortcuts-master. Where am I supposed to place this in the FF installation? I've installed the xpi, and I have the plugin's icon at the top right, and when I click it the dialog opens, but it doesn't do anything. the buttons are grayed out. I can type in the search field but there is nothing to search for. I'm guessing that's because it is not properly installed. Thanks.

**Comment by Keith94** [comment]
Maybe you have another add-on installed that could cause the issue? According to #71 there are some issues with using Tab Mix Plus or keyconfig together with Customizable Shortcuts.

**Comment by IMeanReallyNow** [comment]
Thanks. That was it. Tab Mix Plus. As soon as I disabled it, customizable-shortcuts worked. 

Bummer. 

Just a shot in the dark: Would there be any way to use c-s- to set shortcuts in such a way that the plugin itself didn't have to be enabled (eg for editing or creating new shortcuts) once they had been set, and that would allow TMP to be re-enabled. .

**Comment by Keith94** [comment]
What version of Tab Mix Plus are you using? I can reproduce the bug with an older version (0.4.1.5.2), but after installing 0.4.1.6 (latest) the bug is fixed.

And from my testing, I could disable TMP 0.4.1.5.2, change the shortcuts as needed, enable TMP, and the custom shortcuts still work. Except to change shortcuts again you have to temporarily disable TMP.

**Comment by IMeanReallyNow** [comment]
Ah ha. Thank you! I should have looked to see if Tab Mix Plus was updated. I was using 0.4.5.2, on a Portable Firefox I thought was up to date. After updating, to 0.4.1.6, it and c-s are working as I'd expect them to. 

This is fantastic. I've wanted a good shortcuts customizer forever, But TMP would have been hard to give up. Now I've got them both.

**Comment by Keith94** [comment]
Glad to hear it. :)
