### ISSUE TITLE
settings lost when Firefox exits unexpectedly

### ISSUE THREAD

**Issue by lucisandor** [ttaubert/customizable-shortcuts#78]
Turn off the computer while Firefox shows 10 tabs. If upon rebooting, Firefox displays the menu for restoring tabs, it's a given Firefox didn't exit cleanly, and Customizable Shortcuts forgot its settings. Same goes for Firefox crashes caused by Flash.
Using latest Firefox 34 and Customizable Shortcuts 0.6.2.

**Comment by ttaubert** [comment]
I'm only using the simple-storage module provided by the SDK. I might not be able to fix this.

**Comment by ttaubert** [comment]
Sorry.
