### ISSUE TITLE
next / previous tab customizable shortcut

### ISSUE THREAD

**Issue by sonnyp** [ttaubert/customizable-shortcuts#79]
Am I missing something or this isn't one of the customizable shortcut?

I'll happily send a PR.

**Comment by Keith94** [comment]
It's already implemented in v0.9.0 per 9895b24

**Comment by trvrfrd** [comment]
The version available on the official site is 0.6.2, when can we expect 0.9.0 to be available through AMO?

**Comment by monperrus** [comment]
I need this feature. Where can I download the beta of 0.9?

**Comment by Keith94** [comment]
Right here: https://github.com/ttaubert/customizable-shortcuts/raw/master/customizable-shortcuts.xpi
