### ISSUE TITLE
New Tab option missing

### ISSUE THREAD

**Issue by poodle123** [ttaubert/customizable-shortcuts#80]
Hi,

had the problem of not beeing able to use umlauts (öäü) in the regular version. I was using the addon to swap function for CTRL+N with CTRL+T (i.e. CTRL+N opens a new Tab). However when updating to the version here the shortcut from File - New Tab disappeared and cant be set anymore. Now I cant use CtRL+T at all. Tried to remove the addon, still no luck. The shortcut CTRL+T is totally missing. Any way to restore it? Will reinstalling Firefox over itself help? Dont want to loose all my settings ....

**Comment by ttaubert** [comment]
Please try again with the latest XPI in the repository.
