### ISSUE TITLE
Installed 0.90 but nothing shows up

### ISSUE THREAD

**Issue by auralarch** [ttaubert/customizable-shortcuts#81]
After installing the new version there is no trace of it to be found besides being in the list of enabled add-ons.  No toolbar icon.  Tried "customizing" the toolbar but the icon isn't there at all with other  buttons I've removed from the toolbar- and hence I have no way of using the extension by accessing the customization window.  It seems like this could be avoided if there were a "Preferences" button for it in the add-ons manager like most others have; but I'm sure there must be a good why you have it setup the way you do & there isn't a button...
I am using FF ESR  31.4.0 (latest release) for Mac in Mountain Lion- OS X 10.8.5.

I noticed that issues were reported regarding possible (presumed) incompatibilities with keyconfig & TabMixPlus and possibly with FF ESR.  I disabled keyconfig & tabmixplus and restarted to check if that resolved the issue, but it unfortunately didn't seem to have any effect.
If there are unresolvable incompatibilities between keyconfig & customizable-shortcuts, I can deal without keyconfig.  However, if there turns out to either TabMixPlus or FF ESR that would be a real shame & I'd have to wait until/if a compatible version of Customizable-Shortcuts becomes available. Or check-out keyconfig to see if it can handle the changes I need to me (I actually never used it- I had only just installed it when I installed the new version of Customizable-Shortcuts).
It could also be related to one of the other add-ons I've got installed.  Are there any established incompatibilities to with add-ons or anything that you know of?  I didn't see any definites listed on the info page or in the issues.
I hope to find time to be able to do some more intense troubleshooting over the weekend if you don't have any suggestions or ideas.

Other plugins installed: Adblock Plus, Blur, Clean Links, Context Search X, DownloadHelper, DuckDuckGo Plus, Google Translator, Greasemonkey, Image Zoom, Keychain Services Integration, Lazarus, Menu Editor, RightToClick Save as PDF, Session Manager, SmartVideo for YouTube, Text Highlighter, Tree Style Tabs, TrueSuite Weblogin, VLC Context menu
All updated to current release.  Please let me know if any other information may be pertinent to unraveling this issue & I'd be happy to provide it.

Thank you so much for you time & consideration!

**Comment by FredMcD-HotMail** [comment]
Please read this; https://github.com/ttaubert/customizable-shortcuts/issues/83

**Comment by auralarch** [comment]
Thank you!  Much appreciated link to solution...
