### ISSUE TITLE
no userinterface in Fx 37

### ISSUE THREAD

**Issue by RealRaven2000** [ttaubert/customizable-shortcuts#82]
I understand you modify the main options dialog. this doesn;'t exist in Fx37, it is shown in a content tab instead. where are your settings?

**Comment by FredMcD-HotMail** [comment]
https://github.com/ttaubert/customizable-shortcuts/issues/83

**Comment by ttaubert** [comment]
v0.9 is meant to address this. Hope I can get it ready in time...
