### ISSUE TITLE
Current Firefox not show Customizable Shortcuts on new options menu > cure ! !

### ISSUE THREAD

**Issue by FredMcD-HotMail** [ttaubert/customizable-shortcuts#83]
The new Firefox options menu no longer has a place for the Customizable Shortcuts options menu.

To switch back to the old options menu that will show Customizable Shortcuts options,
Type "about:config"<Enter> in the address bar.
If a warning screen comes up, press the "Be Careful" button.
This is where Firefox finds information it needs to run.
At the top of the screen is a search bar. Type "browser.preferences.inContent."
Once that entry, change it to "false."

**Comment by auralarch** [comment]
In a brand-new, fresh profile running Firefox ESR 31.5.0 (latest version) on OS X 10.8.5 I installed Customizable Shortcuts 0.9.0. Upon following the instructions above I discovered that it was already set to "false" and yet I still have no access to UI.

Any other ideas for workarounds/solutions? Suggestions? Thoughts?

Thank you!!!

**Comment by FredMcD-HotMail** [comment]
This works in normal Firefox. Try to open the options from ''about:home''

**Comment by auralarch** [comment]
Thank you! This method works in Firefox ESR 31.5.0 on Windows 7, but I have no success with Mountain Lion for some reason (even in a fresh new profile).  I haven't had a chance to test the normal release of FF, and I am unable to text any other versions of OS X at this time..
(not sure if my original symptoms are exactly the same...  that is: the toolbar button to summon the config UI is missing.  I got the idea (possibly erroneously) that for someone the config UI failed to present (presumably when clicking the toolbar button- hence it was not missing)...

In any case this gives me a few things to try when I get back to my Mac-  thank you!
