### ISSUE TITLE
Customizable Shortcuts 0.6.2 does not respect Close Window shortcut

### ISSUE THREAD

**Issue by penalvch** [ttaubert/customizable-shortcuts#84]
Customizable Shortcuts 0.6.2 does not respect Close Window shortcut.

I've changed the Ctrl+Q to Ctrl+Shift+W so I wouldn't accidentally kill the window with a bunch of tabs open. However, apparently after some Firefox update, this is no longer working.

lsb_release -rd
Description:	Ubuntu Vivid Vervet (development branch)
Release:	15.04

apt-cache policy firefox
firefox:
  Installed: 37.0+build2-0ubuntu1
  Candidate: 37.0+build2-0ubuntu1
  Version table:
 *** 37.0+build2-0ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by ttaubert** [comment]
Please try the latest XPI in the repository (v0.9), I don't maintain 0.6.2 anymore.

**Comment by penalvch** [comment]
ttaubert, thanks for the fast response. Latest XPI works fine. Could this version (0.9) please be loaded to the main website since it's the only one that's supported now?

**Comment by ttaubert** [comment]
Yeah, I'm working on fixing the latest issues and hope to release it soon.
