### ISSUE TITLE
Reassigned shortcut does not work in second window

### ISSUE THREAD

**Issue by Smile4ever** [ttaubert/customizable-shortcuts#86]
Assigning a new shortcut (F1 for example) to Easy Copy - Copy URL (https://addons.mozilla.org/nl/firefox/addon/easy-copy/) results in a working shortcut only for the first window. Pressing F1 in the second window copies the location URL from the first window instead of the second window. Assigning with keyconfig + Easy Copy works, but not with Customizable Shortcuts.

**Comment by ttaubert** [comment]
WFM with the latest .xpi in the repository (v0.9).

**Comment by Smile4ever** [comment]
It does work, thank you!
