### ISSUE TITLE
2015-05-09 version doesn't store commands

### ISSUE THREAD

**Issue by Patuta** [ttaubert/customizable-shortcuts#89]
I was happy to see the "empty board" issue and the "Umlaut" issue being resolved. But customizable-shortcuts still doesn't work for me. I can change key commands but they're not beeing stored. After closing and relaunching Firefox the amended commands are gone.
Maybe there's still an interference with the addon keyconfig?

**Comment by ttaubert** [comment]
I can't reproduce this. With and without keyconfig installed the modifications are stored. Can you see any errors in the console?

**Comment by Patuta** [comment]
I tried again deactivating all other addons but it still happens. 
On the left you see customizable-shortcuts with a adjusted key stroke, on the right customizable-shortcuts after restart: keystroke is gone.
![Before-after](https://cloud.githubusercontent.com/assets/8776027/7550602/51c7886e-f668-11e4-8733-5a102c77ed44.jpg)

**Comment by ttaubert** [comment]
Can you please try the latest .xpi (v0.9.3) with a least Firefox 38 (currently Beta)? I'll target 38+ with v0.9 and there might be bugs in previous Firefox versions?

If that still doesn't work could you try with a new and clean profile? I tried with multiple machines and it always works for me.

**Comment by Smile4ever** [comment]
It is also an issue for me in Firefox 37. Using Firefox Developer (at v39) this problem does not occur.

**Comment by ttaubert** [comment]
What about 38? Sounds like something that's caused by Firefox then...

**Comment by Smile4ever** [comment]
Hi. With using Firefox 38 and Customizable Shortcuts from master xpi (just ago) I see the following:
- clean profile -> works
- upgraded profile from v37 -> doesn't work (keyconfig was never installed in this profile in v37)

**Comment by ttaubert** [comment]
Thanks for reporting back! I will give that a try and see if I can reproduce.

**Comment by ttaubert** [comment]
Alright, think I figured it out. The old configuration data from v0.6.2 is stored under the same key as v0.9's data. That doesn't quite work, I should simply use a different key as the data isn't migrated anyway.
