### ISSUE TITLE
Icon not visible

### ISSUE THREAD

**Issue by florian49** [ttaubert/customizable-shortcuts#91]
Hi there,
I installed the extension but the icon is not visible (see screenshot)
![unbenannt](https://cloud.githubusercontent.com/assets/12450313/7639931/06befe94-fa80-11e4-9af6-04df98ce3a4b.JPG)
. I use Firefox Version 38 - restarted separate times, reinstalled the extension without any luck. 

Thanks for helping out

**Comment by wotangjing** [comment]
You can reference to website "https://github.com/ttaubert/customizable-shortcuts/issues/83" which setting the "browser.preferences.inContent" to false in about:config.
Or using  the lastest version 0.9.5, you can download  from https://github.com/ttaubert/customizable-shortcuts.But I found a bug that it can't difference the number key form number.

**Comment by ttaubert** [comment]
Florian, are you using the latest version 0.9.5? Can find the XPI in the master branch.

**Comment by florian49** [comment]
Hey all, thanks for the fast response - I tried to install the newest version but firefox declines with "this addon seems to be faulty"

**Comment by ttaubert** [comment]
Did you try this link?

https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.5.xpi?raw=true

Right-click and "Save as" should work.

**Comment by florian49** [comment]
Thanks, your link worked and it is working now - Would be great to see the mozilla rep be updated to the current version.

The attribute (raw) seems to make the difference - I tried this one before:
https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts%40timtaubert.de-0.9.5.xpi

**Comment by ttaubert** [comment]
Thanks for reporting back! Yes, I'm waiting for the add-on to be reviewed. Hope that is done soon.
