### ISSUE TITLE
customizable-shortcuts doesn't work with new firefox preferences menu

### ISSUE THREAD

**Issue by brunorey** [ttaubert/customizable-shortcuts#92]
Since my last update, I can't find the shortcuts section in the new preferences settings: 

![Screenshot for reference](http://cdn.ghacks.net/wp-content/uploads/2014/03/firefox-about-preferences.png)

Any comment on this?

**Comment by ath0mas** [comment]
Issue related to Firefox 38+ Preferences panel

**Comment by ttaubert** [comment]
Please use the new version on GitHub:

https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.5.xpi?raw=true

It's waiting for approval on addons.mozilla.org currently.
