### ISSUE TITLE
I can't override default shortcuts

### ISSUE THREAD

**Issue by 3v1n0** [ttaubert/customizable-shortcuts#93]
Hi,
I've just upgraded to Firefox 38 and to customizable-shortcuts 0.9.5

However, it seems that some default shortcuts (such as Print, or New Private Window) shortcuts can't be overridden. 
For example for Ctrl+P, I've tried both to set this to a different shortcut and disabling it, but in any case the Print dialog pops-up when using the keybinding (together with the other action I've set for that).
This used to work in previous versions.

It seems that for all the shortcuts the default key-binding is not disabled.

**Comment by ttaubert** [comment]
WFM on OS X. Are you using Linux?

**Comment by 3v1n0** [comment]
Yeah, sorry I didn't go into the details...

This is with Ubuntu 14.04 and Firefox 38 (from ubuntu archives)

**Comment by 3v1n0** [comment]
I've removed my old $PROFILE_PATH/jetpack/customizable-shortcuts@timtaubert.de/simple-storage/store.json and now the old keybindings doesn't work anymore.

For your information, my "broken" store.json contained this http://pastebin.ubuntu.com/11225046/ (while new one looks simpler http://paste.ubuntu.com/11225056/).

However, now I've another problem... But I'll open a new bug for that since I've already done so much mess here (sorry about that!).

**Comment by ttaubert** [comment]
That's weird, I actually use a different storage key so that old settings don't interfere with the new format.

**Comment by 3v1n0** [comment]
Yep, I've noticed it... But it's just what has happened to me :o
