### ISSUE TITLE
Extensions can't re-use default keybindings once disabled

### ISSUE THREAD

**Issue by 3v1n0** [ttaubert/customizable-shortcuts#95]
* Disable a default shortcut (i.e. `Ctrl+P,` `Ctrl+R`...)
* Associate that shortcut to another extension (such as [All Tabs Helper](https://addons.mozilla.org/en-US/firefox/addon/all-tabs-helper/?src=api) or [Tabhunter](https://addons.mozilla.org/en-US/firefox/addon/tabhunter/)).
* The shortcut won't work for the extension, unless you don't enable it again globally (causing two actions to happen).

I'm not sure whether the problem is in this extension or in firefox, though. So sorry if it's out of this scope.

**Comment by ttaubert** [comment]
It's really hard to detect (maybe impossible?) that you reassigned the shortcut to another extension. You would just need to reenable it to make it work, so luckily there's an easy solution. I don't think this is a very common scenario to address... Thanks for reporting it though!
