### ISSUE TITLE
How to remove default shortcut

### ISSUE THREAD

**Issue by nakinigit** [ttaubert/customizable-shortcuts#96]
In Ubuntu, I use nano as my text editor, ctrl+w being one of my favourite keystrokes to search for text. That is also the exact same keystroke to close a tab in firefox. 

How do I forever delete that shortcut, using your ad-on, in firefox? I can see how to edit it, but I want it deleted.

Sorry, user error on my part for not properly identifying active window, but in an multi monitor environment, is easy to overlook.

**Comment by ttaubert** [comment]
You can simply disable that shortcut in the latest version of the add-on. You can get it here:

https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/versions/?page=1#version-0.9.5
