### ISSUE TITLE
Shortcut Settings Menu inaccessible after Firefox Update 38

### ISSUE THREAD

**Issue by eraz** [ttaubert/customizable-shortcuts#97]
The Firefox Options menu was redesigned and given its own page (about:preferences).

Forefox no longer creates a pop-up window like before, thus the Customizable Shortcuts menu is inaccessible, as it does not appear in the new Options tab, is not available in the Tools menu, and does not have an "options" button in the Add-ons page.

**Comment by Keith94** [comment]
See solution: #92

**Comment by eraz** [comment]
Ah, my mistake.

Note to self: don't forget to check the closed issues tab before posting. :)
