### ISSUE TITLE
[FreeBSD] Unable to install from addons site v0.9.5

### ISSUE THREAD

**Issue by scfarley** [ttaubert/customizable-shortcuts#98]
I am unable to install v0.9.5 from AMO on a FreeBSD system.  v0.6.2 can be installed.  I see "Not available for your platform".

**Comment by ttaubert** [comment]
"jpm xpi" and then uploading to AMO seems to only provide Win/Linux/Mac versions. I don't think I did anything special with the previous version (0.6.2) to make it work on FreeBSD... Not sure what I can do about that.

**Comment by scfarley** [comment]
Is there an option for no platform?  Possibly, selecting platforms does something automatically to exclude others.  I have run into this before with Adblock Edge.  I left a comment here about that:  https://bitbucket.org/adstomper/adblockedge/issue/20/#comment-14812258  For all I know, it could be a different issue and/or different solution.

**Comment by LOursPOlaiR** [comment]
I'm under windows 7 64b FR
I can't install 0.9.6, add on site prupose only the 0.6.2...

What is wrong ?

**Comment by ttaubert** [comment]
That is a very different problem, I'm still waiting for the add-on to be reviewed. "Queue Position: 153 of 207" after more than two weeks :/

**Comment by LOursPOlaiR** [comment]
Holly cow, 153 of 207 after two weeks !!!
Is there a another way to get this brillant extension ?

**Comment by ttaubert** [comment]
You can install it from here:

https://github.com/ttaubert/customizable-shortcuts/blob/master/customizable-shortcuts@timtaubert.de-0.9.6.xpi?raw=true

Either you can install it directly or download it and drag&drop it onto the browser.

**Comment by LOursPOlaiR** [comment]
Thank you very much !

**Comment by wcrighton** [comment]
Very nice support - I just watched the page and the solution came through the notifications - on Ubuntu 14.04.02 / Mozilla Firefox 38.0 the only available version for this shows up as 0.6.2

Thanks for the support, it is such a time suck. 
Thank you very much

**Comment by ttaubert** [comment]
I don't think I can fix this, sorry :(

**Comment by scfarley** [comment]
I had forgotten about this issue.  I just want to report that with v0.9.8, AMO has it installable on FreeBSD.  Something is happier with the setup.

**Comment by ttaubert** [comment]
Great!
