### ISSUE TITLE
Can't see addon button

### ISSUE THREAD

**Issue by argamanza** [ttaubert/customizable-shortcuts#99]
currently using Firefox 38.0.1, after add on installation and restarting my browser i can't find the add on button anywhere.

**Comment by zeldasf** [comment]
I am having this same problem with Firefox 38.0.1 on a Mac OSX 10.6.8. The button is appearing neither in the toolbar nor the "Additional Tools and Features".
![screen shot 2015-05-26 at 22 38 16](https://cloud.githubusercontent.com/assets/12616830/7822939/1ca0391c-03f9-11e5-8d64-f9f726cfd7e8.png)

**Comment by ttaubert** [comment]
Please install v0.9.6 that is currently pending review and will probably be for a while:

https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/versions/?page=1#version-0.9.6
